apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    type: infra
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      type: infra
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
        type: infra
    spec:
      containers:
        - name: nginx-container
          image: nginx

