apiVersion: v1
kind: ResourceQuota
metadata:
  name: test-quota
  namespace: test

spec:
  hard:
    pods: 10
    requests.cpu: "4"
    requests.memory: 5Gi
    limits.cpu: "10"
    limits.memory: 10Gi
