apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  labels:
    app: nginx
    type: infrastruture

spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
        type: infrastrucutre
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
