apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret-pod
  labels:
    app: nginx
    type: infra

spec:
  containers:
    - image: nginx
      name: nginx-container
      envFrom:
        - secretRef:
            name: nginx-secret

