apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    app: redis
    type: infra

spec:
  containers:
    - name: redis-container
      image: redis
      command: ["docker-entrypoint.sh"] # replace the ENTRYPOINT on Dockerfile
                                        # this is the default redis docker image entrypoint

      args: ["redis-server"]  # replace the CMD on Dockerfile image
                              # this is the default redis docker image command
                              # the redis docker entrypoint is ["docker-entrypoint.sh"]
