apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret-volume-pod
  labels:
    app: nginx
    type: infra

spec:
  volumes:
    - name: nginx-secret-volume
      secret:
        secretName: nginx-secret
  containers:
    - image: nginx
      name: nginx-container
