apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret

data:
  MY_KEY: bXlfdmFsdWU=  # this value is encoded using base64
                        # encode: echo -n 'my_value' | base64
                        # decode: echo -n 'bXlfdmFsdWU=' | base64 -d

